name: Compile LaTeX document

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'  # This will run the workflow daily at midnight UTC

permissions:
  contents: write  # Explicitly set the permission for the GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner != 'hanisntsolo'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Use Node.js 20 or latest

      - name: Create output directory
        run: mkdir -p output

      - name: Set up LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: hanisntsolo-resume.tex
          extra_system_packages: "inkscape"
          compiler: xelatex  # Use latexmk to compile the document
          args: -shell-escape -output-directory=output  # Specify output directory and add shell-escape flag

      - name: Install Node dependencies
        run: npm install

      - name: Build React Timeline (Production)
        run: npm run build:prod

      - name: Copy React app build to output
        run: cp -r dist/* output/

      - name: Add CNAME file for Custom Domain
        run: echo "hanisntsolo.hanisntsolo.com" > output/CNAME
        
      - name: List files in output directory
        run: tree output

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output  # Directory containing your compiled PDF
          destination_dir: ./  # Directory where the site will be hosted
