name: Compile LaTeX document

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'  # This will run the workflow daily at midnight UTC

permissions:
  contents: write  # Explicitly set the permission for the GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Use Node.js 20 or latest

      - name: Set up LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: __GITHUB_USERNAME__-resume.tex
          extra_system_packages: "inkscape"
          compiler: xelatex  # Use latexmk to compile the document
          args: -shell-escape -output-directory=output  # Specify output directory and add shell-escape flag

      - name: Copy index.html to output
        run: cp index.html output/index.html  # Copy index.html to output directory

      - name: Add CNAME file for Custom Domain
        run: echo "resume.__GITHUB_USERNAME__.com" > output/CNAME
        
      - name: List files in output directory
        run: tree output

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output  # Directory containing your compiled PDF
          destination_dir: ./  # Directory where the site will be hosted
