name: Compile LaTeX document for Hanisntsolo

on:
  repository_dispatch:
    types: [trigger-hanisntsolo]
  push:
    branches:
      - hanisntsolo

permissions:
  contents: write  # Explicitly set the permission for the GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'hanisntsolo'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Use Node.js 20 or latest

      - name: Create output directory
        run: mkdir -p output

      - name: Compile Original Resume (Visual)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: hanisntsolo-resume.tex
          extra_system_packages: "inkscape"
          compiler: xelatex
          args: -shell-escape -output-directory=output

      - name: Compile ATS-Optimized Resume
        uses: xu-cheng/latex-action@v3
        with:
          root_file: hanisntsolo-resume-ats.tex
          extra_system_packages: "inkscape"
          compiler: xelatex
          args: -shell-escape -output-directory=output

      - name: Compile ATS-Optimized Cover Letter
        uses: xu-cheng/latex-action@v3
        with:
          root_file: hanisntsolo-cover-letter.tex
          extra_system_packages: "inkscape"
          compiler: xelatex
          args: -shell-escape -output-directory=output

      - name: Install Node dependencies
        run: npm install

      - name: Build Astro site (Production)
        run: npm run build

      - name: Copy site build to output
        run: |
          find dist -mindepth 1 -maxdepth 1 \
            ! -name 'hanisntsolo-resume.pdf' \
            ! -name 'hanisntsolo-cover-letter.pdf' \
            -exec cp -r {} output/ \;

      - name: Add CNAME file for Custom Domain
        run: echo "resume.hanisntsolo.com" > output/CNAME
        
      - name: List files in output directory
        run: tree output

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output  # Directory containing your compiled PDF
          destination_dir: ./  # Directory where the site will be hosted
