name: First-Time Setup

on:
  workflow_dispatch:
  push:
    branches:
      - master  # Change to 'main' if needed

permissions:
  contents: write
  pull-requests: write

jobs:
  personalize:
    name: Personalize fork with user handle
    if: github.repository_owner != 'hanisntsolo'
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}  # PAT with repo + workflow scopes

      - name: Set GitHub handle env var
        run: echo "GITHUB_HANDLE=${{ github.repository_owner }}" >> $GITHUB_ENV

      - name: Replace handle placeholders in file contents
        run: |
          echo "Replacing 'hanisntsolo' with '${GITHUB_HANDLE}' in file contents"
          grep -rl --exclude-dir=".git" --exclude="*.pdf" 'hanisntsolo' . | while read -r file; do
            sed -i "s/hanisntsolo/${GITHUB_HANDLE}/g" "$file"
          done

      - name: Rename files and folders with handle
        run: |
          echo "Renaming all files and folders containing 'hanisntsolo' to '${GITHUB_HANDLE}'"
          find . -depth -name "*hanisntsolo*" | while read -r path; do
            new_path=$(echo "$path" | sed "s/hanisntsolo/${GITHUB_HANDLE}/g")
            if [ "$path" != "$new_path" ]; then
              echo "Renaming $path -> $new_path"
              mv "$path" "$new_path"
            else
              echo "Skipping rename for $path (no change)"
            fi
          done



      - name: Commit and push changes to new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # default token for gh CLI
        run: |
          git switch -c personalize-${GITHUB_HANDLE}

          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          if git diff --cached --quiet; then
            echo "No changes detected. Skipping commit and PR creation."
            exit 0
          fi

          git commit -m "chore: personalize repo for @${GITHUB_HANDLE}"
          git push --set-upstream origin personalize-${GITHUB_HANDLE}

          gh pr create \
            --title "chore: personalize repo for @${GITHUB_HANDLE}" \
            --body "This PR personalizes the template with the fork owner's GitHub handle."

