name: First-Time Setup

with:
    token: ${{ secrets.WORKFLOW_TOKEN }}
  # This token is used to authenticate the action
  # and allows it to push changes back to the repository.
permissions: write-all
  # contents: write
  # workflows: write  # Allow workflow modification permissions for this action

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI
  push:
    branches:
      - master  # Change to 'main' if your default branch is 'main'

jobs:
  personalize:
    if: github.repository_owner != 'hanisntsolo'  # Run only for forks, not the original repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set GitHub handle env var
        run: echo "GITHUB_HANDLE=${{ github.repository_owner }}" >> $GITHUB_ENV

      - name: Replace handle placeholders in all files
        run: |
          echo "Replacing all occurrences of '__GITHUB_USERNAME__' with '${GITHUB_HANDLE}'"
          grep -rl --exclude-dir=".git" --exclude="*.pdf" '__GITHUB_USERNAME__' . | while read -r file; do
            sed -i "s/__GITHUB_USERNAME__/${GITHUB_HANDLE}/g" "$file"
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "chore: personalize repo with fork owner's handle [skip ci]"
          git push
